# docs_dir: docs
site_name: La Biblioteca de Humanbyte
repo_url: https://github.com/terracenter/biblioteca
site_author: Terracenter

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    # # - content.tabs.link
    # # - content.code.annotation
    # # - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo oscuro
      primary: tealblue grey
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo claro
      primary: blue
      accent: lime

extra_css:
    - stylesheets/extra.css      

plugins:


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terracenter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/terracenter0
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/freddy-taborda-5199802a/
  analytics:
    provider: google
    property: G-5T8Q8F61MQ
    feedback:
      title: ¿Te ha resultado útil esta página?
      ratings:
        - icon: material/thumb-up-outline
          name: ¿Te ha resultado útil esta página?
          data: 1
          note: >-
            Gracias por sus comentarios.
        - icon: material/thumb-down-outline
          name: Esta página podría mejorarse
          data: 0
          note: >- 
            Gracias por sus comentarios. Ayúdenos a mejorar esta página utilizando nuestro <a href="..." target="_blank" rel="noopener">formulario de comentarios</a>.


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details  
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: 
  Copyright &copy; 2024 <a href="https://github.com/terracenter target="_blank" rel="noopener"> Freddy Taborda </a>

  